# Generated by Django 5.1.1 on 2024-10-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16)),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('when_added', models.DateTimeField(auto_now_add=True)),
                ('img', models.ImageField(upload_to='images/products/')),
                ('discount', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField()),
                ('brand', models.CharField(max_length=32)),
            ],
        ),
    ]
